"""edit_department_model_name_unique

Revision ID: 024ba9dc187a
Revises: 7e56928e97dd
Create Date: 2025-01-22 12:05:01.307497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024ba9dc187a'
down_revision: Union[str, None] = '7e56928e97dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departments', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='unique')
    # ### end Alembic commands ###
