"""edit user model

Revision ID: 2d1ecd59334c
Revises: b3b7314ced09
Create Date: 2025-01-15 13:41:26.688050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1ecd59334c'
down_revision: Union[str, None] = 'b3b7314ced09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###
