"""edit_department_model

Revision ID: 7e56928e97dd
Revises: 2d1ecd59334c
Create Date: 2025-01-22 11:42:12.945491

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e56928e97dd"
down_revision: str | None = "2d1ecd59334c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("departments", sa.Column("parent_department_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "departments", "departments", ["parent_department_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "departments", type_="foreignkey")
    op.drop_column("departments", "parent_department_id")
    # ### end Alembic commands ###
