"""edit_user_moodel

Revision ID: 811643436f09
Revises: 69875032f8c8
Create Date: 2025-01-22 18:59:00.964620

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "811643436f09"
down_revision: str | None = "69875032f8c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_position_id_fkey", "users", type_="foreignkey")
    op.drop_column("users", "position_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("position_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("users_position_id_fkey", "users", "positions", ["position_id"], ["id"])
    # ### end Alembic commands ###
