"""edit_department_model_head_id_nullable

Revision ID: ac55515a2f31
Revises: 024ba9dc187a
Create Date: 2025-01-22 12:42:33.835066

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac55515a2f31"
down_revision: str | None = "024ba9dc187a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "head_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "head_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
