"""0003_add_repartment_position

Revision ID: b37cafb5360e
Revises: dc173a17b7cd
Create Date: 2025-01-14 14:01:26.767286

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b37cafb5360e"
down_revision: str | None = "dc173a17b7cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS ltree"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("departments",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("path", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False),
    sa.Column("company_id", sa.Integer(), nullable=False),
    sa.Column("head_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
    sa.ForeignKeyConstraint(["head_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("positions",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("department_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["department_id"], ["departments.id"]),
    sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("position_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "users", "positions", ["position_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "position_id")
    op.drop_table("positions")
    op.drop_table("departments")
    # ### end Alembic commands ###
