"""fixes

Revision ID: b3b7314ced09
Revises: b37cafb5360e
Create Date: 2025-01-15 13:30:42.277419

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b3b7314ced09"
down_revision: str | None = "b37cafb5360e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
