"""0002_user_password_nullable

Revision ID: dc173a17b7cd
Revises: 1e41c0556a32
Create Date: 2024-12-23 13:58:22.068025

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc173a17b7cd"
down_revision: str | None = "1e41c0556a32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password",
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password",
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
